### ISSUE TITLE
Events created by Enlighten do not save properly

### ISSUE THREAD

**Issue by the-Astra** [Swifter1243/Enlighten#1]
Any events created with Enlighten change to fit a linear gradient as opposed to what was being shown prior to saving

https://github.com/Swifter1243/Enlighten/assets/75325082/0e3d2f25-7a6f-42cb-b024-5fd90d8c560c

**Comment by Swifter1243** [comment]
I knew about this I was just Lazy but now that I've been found out I fixed it <3
